package com.jaac.avoqado_tpv.features.authentication.data.dto

import com.google.gson.annotations.SerializedName
import com.jaac.avoqado_tpv.features.authentication.domain.models.*

/**
 * PIN Login Request DTO
 *
 * Network request for PIN authentication.
 * Maps to backend schema: `{ pin: string, serialNumber: string }`
 *
 * ⚠️ BREAKING CHANGE (2025-01-03):
 * Backend now requires serialNumber to validate terminal activation status.
 * This prevents login on deactivated terminals.
 */
data class PinLoginRequestDto(
    @SerializedName("pin") val pin: String,
    @SerializedName("serialNumber") val serialNumber: String
)

/**
 * Master TOTP Login Request DTO
 *
 * Network request for SUPERADMIN emergency access via TOTP.
 * Uses 8-digit codes generated by Google Authenticator (60-second period).
 *
 * ⚠️ SECURITY NOTE:
 * - This grants full SUPERADMIN access to ANY terminal
 * - All master logins are audited (IP, terminal, timestamp)
 * - Only use for emergency support access
 */
data class MasterLoginRequestDto(
    @SerializedName("totpCode") val totpCode: String,
    @SerializedName("serialNumber") val serialNumber: String
)

/**
 * Authentication Response DTO
 *
 * Network response from successful authentication.
 * Maps to backend `staffSignIn` response.
 */
data class AuthResponseDto(
    // Auth tokens
    @SerializedName("accessToken") val accessToken: String,
    @SerializedName("refreshToken") val refreshToken: String,
    @SerializedName("expiresIn") val expiresIn: Int,
    @SerializedName("tokenType") val tokenType: String,

    // Auth context
    @SerializedName("staffId") val staffId: String,
    @SerializedName("venueId") val venueId: String,
    @SerializedName("role") val role: String,
    @SerializedName("permissions") val permissions: List<String>?,

    // Staff details
    @SerializedName("staff") val staff: StaffMemberDto,
    @SerializedName("venue") val venue: VenueInfoDto,

    // Metadata
    @SerializedName("correlationId") val correlationId: String,
    @SerializedName("issuedAt") val issuedAt: String,

    // 🎁 Loyalty program status (Toast/Square pattern: hide UI if inactive)
    @SerializedName("loyaltyActive") val loyaltyActive: Boolean? = false,

    // 🔐 Master TOTP login flag - bypasses venue rules (clock-in, etc.)
    @SerializedName("isMasterLogin") val isMasterLogin: Boolean? = false,

    // Custom role display name configured in dashboard (e.g., "Bartender" instead of "Mesero")
    @SerializedName("roleDisplayName") val roleDisplayName: String? = null
)

/**
 * Staff Member DTO
 *
 * Staff information from backend.
 */
data class StaffMemberDto(
    @SerializedName("id") val id: String,
    @SerializedName("firstName") val firstName: String,
    @SerializedName("lastName") val lastName: String,
    @SerializedName("email") val email: String?,
    @SerializedName("phone") val phone: String?,
    @SerializedName("employeeCode") val employeeCode: String?,
    @SerializedName("photoUrl") val photoUrl: String?,
    @SerializedName("active") val active: Boolean
)

/**
 * Venue Info DTO
 *
 * Venue context from backend.
 * Includes status field for operational state tracking.
 */
data class VenueInfoDto(
    @SerializedName("id") val id: String,
    @SerializedName("name") val name: String,
    @SerializedName("slug") val slug: String?,  // 📸 For Firebase Storage path: venues/{slug}/verifications/
    @SerializedName("posType") val posType: String?,
    @SerializedName("posStatus") val posStatus: String?,
    @SerializedName("logo") val logo: String?,
    @SerializedName("status") val status: String? = null
)

/**
 * Refresh Token Request DTO
 */
data class RefreshTokenRequestDto(
    @SerializedName("refreshToken") val refreshToken: String
)

/**
 * Refresh Token Response DTO
 */
data class RefreshTokenResponseDto(
    @SerializedName("accessToken") val accessToken: String,
    @SerializedName("expiresIn") val expiresIn: Int,
    @SerializedName("tokenType") val tokenType: String
)

/**
 * Staff Permissions Response DTO
 *
 * Response from GET /tpv/auth/permissions endpoint.
 * Contains resolved permissions for the authenticated staff member.
 *
 * Backend response merges:
 * 1. Base permissions from DEFAULT_PERMISSIONS (role-based)
 * 2. Custom permissions from VenueRolePermission (dashboard-configured)
 * 3. Implicit permissions from dependencies
 *
 * **Backend Response Example:**
 * ```json
 * {
 *   "success": true,
 *   "data": {
 *     "staffId": "staff_xxx",
 *     "venueId": "venue_xxx",
 *     "role": "ADMIN",
 *     "permissions": ["tpv-terminal:settings", "tpv-payments:create", ...]
 *   }
 * }
 * ```
 *
 * @param success API success flag
 * @param data Nested data object with staff permissions
 */
data class StaffPermissionsResponse(
    @SerializedName("success") val success: Boolean,
    @SerializedName("data") val data: StaffPermissionsData
)

/**
 * Staff Permissions Data DTO
 *
 * Contains staff identity and resolved permissions list.
 *
 * @param staffId Staff member ID
 * @param venueId Venue ID
 * @param role Staff role (SUPERADMIN, OWNER, ADMIN, MANAGER, CASHIER, WAITER, etc.)
 * @param permissions List of resolved permissions (e.g., ["tpv-terminal:settings", "orders:read"])
 */
data class StaffPermissionsData(
    @SerializedName("staffId") val staffId: String,
    @SerializedName("venueId") val venueId: String,
    @SerializedName("role") val role: String,
    @SerializedName("permissions") val permissions: List<String>
)

// ========== Domain → DTO Mappers ==========

/**
 * Convert domain PinLoginRequest to DTO
 */
fun PinLoginRequest.toDto(): PinLoginRequestDto {
    return PinLoginRequestDto(
        pin = pin,
        serialNumber = serialNumber
    )
}

/**
 * Convert domain RefreshTokenRequest to DTO
 */
fun RefreshTokenRequest.toDto(): RefreshTokenRequestDto {
    return RefreshTokenRequestDto(refreshToken = refreshToken)
}

// ========== DTO → Domain Mappers ==========

/**
 * Convert DTO AuthResponse to domain model
 */
fun AuthResponseDto.toDomain(): AuthResponse {
    return AuthResponse(
        accessToken = accessToken,
        refreshToken = refreshToken,
        expiresIn = expiresIn,
        tokenType = tokenType,
        staffId = staffId,
        venueId = venueId,
        role = StaffRole.fromString(role),
        permissions = permissions ?: emptyList(),
        staff = staff.toDomain(),
        venue = venue.toDomain(),
        correlationId = correlationId,
        issuedAt = issuedAt,
        loyaltyActive = loyaltyActive ?: false,
        isMasterLogin = isMasterLogin ?: false,
        roleDisplayName = roleDisplayName
    )
}

/**
 * Convert DTO StaffMember to domain model
 */
fun StaffMemberDto.toDomain(): StaffMember {
    return StaffMember(
        id = id,
        firstName = firstName,
        lastName = lastName,
        email = email,
        phone = phone,
        employeeCode = employeeCode,
        photoUrl = photoUrl,
        active = active
    )
}

/**
 * Convert DTO VenueInfo to domain model
 */
fun VenueInfoDto.toDomain(): VenueInfo {
    return VenueInfo(
        id = id,
        name = name,
        slug = slug,  // 📸 For Firebase Storage path
        posType = posType,
        posStatus = posStatus,
        logo = logo,
        status = VenueStatus.fromString(status)
    )
}

/**
 * Convert DTO RefreshTokenResponse to domain model
 */
fun RefreshTokenResponseDto.toDomain(): RefreshTokenResponse {
    return RefreshTokenResponse(
        accessToken = accessToken,
        expiresIn = expiresIn,
        tokenType = tokenType
    )
}
