apply plugin: 'com.android.library'

android {
    compileSdkVersion 34  // Updated to match app module
    namespace = "com.paxsz.module.emv"
    defaultConfig {
        minSdkVersion 27  // Updated to match app module (Blumon SDK requirement)
        targetSdkVersion 34  // Updated to match app module
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

    }

    lintOptions {
        abortOnError false
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17  // Updated to match app module
        targetCompatibility JavaVersion.VERSION_17
    }
}

repositories{
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    api fileTree(include: ['*.jar'], dir: 'libs')
    api project(':commonlib')
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.annotation:annotation-jvm:1.7.1'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
